package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hubungan generated by hbm2java
 */
public class Hubungan  implements java.io.Serializable {


     private Integer hubunganId;
     private String nama;
     private Set hubungandetails = new HashSet(0);

    public Hubungan() {
    }

	
    public Hubungan(String nama) {
        this.nama = nama;
    }
    public Hubungan(String nama, Set hubungandetails) {
       this.nama = nama;
       this.hubungandetails = hubungandetails;
    }
   
    public Integer getHubunganId() {
        return this.hubunganId;
    }
    
    public void setHubunganId(Integer hubunganId) {
        this.hubunganId = hubunganId;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Set getHubungandetails() {
        return this.hubungandetails;
    }
    
    public void setHubungandetails(Set hubungandetails) {
        this.hubungandetails = hubungandetails;
    }




}


