package org.siak.data;
// Generated Jul 28, 2012 11:26:38 PM by Hibernate Tools 3.2.1.GA



/**
 * KartukeluargaId generated by hbm2java
 */
public class KartukeluargaId  implements java.io.Serializable {


     private String noKk;
     private String nik;

    public KartukeluargaId() {
    }

    public KartukeluargaId(String noKk, String nik) {
       this.noKk = noKk;
       this.nik = nik;
    }
   
    public String getNoKk() {
        return this.noKk;
    }
    
    public void setNoKk(String noKk) {
        this.noKk = noKk;
    }
    public String getNik() {
        return this.nik;
    }
    
    public void setNik(String nik) {
        this.nik = nik;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KartukeluargaId) ) return false;
		 KartukeluargaId castOther = ( KartukeluargaId ) other; 
         
		 return ( (this.getNoKk()==castOther.getNoKk()) || ( this.getNoKk()!=null && castOther.getNoKk()!=null && this.getNoKk().equals(castOther.getNoKk()) ) )
 && ( (this.getNik()==castOther.getNik()) || ( this.getNik()!=null && castOther.getNik()!=null && this.getNik().equals(castOther.getNik()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoKk() == null ? 0 : this.getNoKk().hashCode() );
         result = 37 * result + ( getNik() == null ? 0 : this.getNik().hashCode() );
         return result;
   }   


}


