package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Kelurahan generated by hbm2java
 */
public class Kelurahan  implements java.io.Serializable {


     private Integer kelurahanId;
     private Kecamatan kecamatan;
     private String nama;
     private int aktif;
     private int kodeDaerah;
     private Set biodatas = new HashSet(0);

    public Kelurahan() {
    }

	
    public Kelurahan(Kecamatan kecamatan, String nama, int aktif, int kodeDaerah) {
        this.kecamatan = kecamatan;
        this.nama = nama;
        this.aktif = aktif;
        this.kodeDaerah = kodeDaerah;
    }
    public Kelurahan(Kecamatan kecamatan, String nama, int aktif, int kodeDaerah, Set biodatas) {
       this.kecamatan = kecamatan;
       this.nama = nama;
       this.aktif = aktif;
       this.kodeDaerah = kodeDaerah;
       this.biodatas = biodatas;
    }
   
    public Integer getKelurahanId() {
        return this.kelurahanId;
    }
    
    public void setKelurahanId(Integer kelurahanId) {
        this.kelurahanId = kelurahanId;
    }
    public Kecamatan getKecamatan() {
        return this.kecamatan;
    }
    
    public void setKecamatan(Kecamatan kecamatan) {
        this.kecamatan = kecamatan;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public int getAktif() {
        return this.aktif;
    }
    
    public void setAktif(int aktif) {
        this.aktif = aktif;
    }
    public int getKodeDaerah() {
        return this.kodeDaerah;
    }
    
    public void setKodeDaerah(int kodeDaerah) {
        this.kodeDaerah = kodeDaerah;
    }
    public Set getBiodatas() {
        return this.biodatas;
    }
    
    public void setBiodatas(Set biodatas) {
        this.biodatas = biodatas;
    }




}


