package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Agama generated by hbm2java
 */
public class Agama  implements java.io.Serializable {


     private Integer agamaId;
     private String nama;
     private Set kartukeluargadetails = new HashSet(0);
     private Set biodatas = new HashSet(0);

    public Agama() {
    }

	
    public Agama(String nama) {
        this.nama = nama;
    }
    public Agama(String nama, Set kartukeluargadetails, Set biodatas) {
       this.nama = nama;
       this.kartukeluargadetails = kartukeluargadetails;
       this.biodatas = biodatas;
    }
   
    public Integer getAgamaId() {
        return this.agamaId;
    }
    
    public void setAgamaId(Integer agamaId) {
        this.agamaId = agamaId;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Set getKartukeluargadetails() {
        return this.kartukeluargadetails;
    }
    
    public void setKartukeluargadetails(Set kartukeluargadetails) {
        this.kartukeluargadetails = kartukeluargadetails;
    }
    public Set getBiodatas() {
        return this.biodatas;
    }
    
    public void setBiodatas(Set biodatas) {
        this.biodatas = biodatas;
    }




}


