package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA



/**
 * Aktanikahdetail generated by hbm2java
 */
public class Aktanikahdetail  implements java.io.Serializable {


     private Integer aktaNikahDetailId;
     private Biodata biodataByNiksuami;
     private Aktanikah aktanikah;
     private Biodata biodataByNikistri;

    public Aktanikahdetail() {
    }

    public Aktanikahdetail(Biodata biodataByNiksuami, Aktanikah aktanikah, Biodata biodataByNikistri) {
       this.biodataByNiksuami = biodataByNiksuami;
       this.aktanikah = aktanikah;
       this.biodataByNikistri = biodataByNikistri;
    }
   
    public Integer getAktaNikahDetailId() {
        return this.aktaNikahDetailId;
    }
    
    public void setAktaNikahDetailId(Integer aktaNikahDetailId) {
        this.aktaNikahDetailId = aktaNikahDetailId;
    }
    public Biodata getBiodataByNiksuami() {
        return this.biodataByNiksuami;
    }
    
    public void setBiodataByNiksuami(Biodata biodataByNiksuami) {
        this.biodataByNiksuami = biodataByNiksuami;
    }
    public Aktanikah getAktanikah() {
        return this.aktanikah;
    }
    
    public void setAktanikah(Aktanikah aktanikah) {
        this.aktanikah = aktanikah;
    }
    public Biodata getBiodataByNikistri() {
        return this.biodataByNikistri;
    }
    
    public void setBiodataByNikistri(Biodata biodataByNikistri) {
        this.biodataByNikistri = biodataByNikistri;
    }




}


