package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aktanikah generated by hbm2java
 */
public class Aktanikah  implements java.io.Serializable {


     private String noAktaNikah;
     private Permohonan permohonan;
     private Date tanggalBuat;
     private int jenisBuat;
     private Set aktanikahdetails = new HashSet(0);

    public Aktanikah() {
    }

	
    public Aktanikah(String noAktaNikah, Permohonan permohonan, Date tanggalBuat, int jenisBuat) {
        this.noAktaNikah = noAktaNikah;
        this.permohonan = permohonan;
        this.tanggalBuat = tanggalBuat;
        this.jenisBuat = jenisBuat;
    }
    public Aktanikah(String noAktaNikah, Permohonan permohonan, Date tanggalBuat, int jenisBuat, Set aktanikahdetails) {
       this.noAktaNikah = noAktaNikah;
       this.permohonan = permohonan;
       this.tanggalBuat = tanggalBuat;
       this.jenisBuat = jenisBuat;
       this.aktanikahdetails = aktanikahdetails;
    }
   
    public String getNoAktaNikah() {
        return this.noAktaNikah;
    }
    
    public void setNoAktaNikah(String noAktaNikah) {
        this.noAktaNikah = noAktaNikah;
    }
    public Permohonan getPermohonan() {
        return this.permohonan;
    }
    
    public void setPermohonan(Permohonan permohonan) {
        this.permohonan = permohonan;
    }
    public Date getTanggalBuat() {
        return this.tanggalBuat;
    }
    
    public void setTanggalBuat(Date tanggalBuat) {
        this.tanggalBuat = tanggalBuat;
    }
    public int getJenisBuat() {
        return this.jenisBuat;
    }
    
    public void setJenisBuat(int jenisBuat) {
        this.jenisBuat = jenisBuat;
    }
    public Set getAktanikahdetails() {
        return this.aktanikahdetails;
    }
    
    public void setAktanikahdetails(Set aktanikahdetails) {
        this.aktanikahdetails = aktanikahdetails;
    }




}


