package org.siak.data;
// Generated Jul 31, 2012 6:51:26 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Aktakematian generated by hbm2java
 */
public class Aktakematian  implements java.io.Serializable {


     private String noAktaKematian;
     private Kartukeluarga kartukeluarga;
     private Permohonan permohonan;
     private Biodata biodata;
     private Date tanggalMeninggal;
     private String tempatMeninggal;
     private String keterangan;
     private String nikayah;
     private String nikibu;
     private int jenisBuat;

    public Aktakematian() {
    }

    public Aktakematian(String noAktaKematian, Kartukeluarga kartukeluarga, Permohonan permohonan, Biodata biodata, Date tanggalMeninggal, String tempatMeninggal, String keterangan, String nikayah, String nikibu, int jenisBuat) {
       this.noAktaKematian = noAktaKematian;
       this.kartukeluarga = kartukeluarga;
       this.permohonan = permohonan;
       this.biodata = biodata;
       this.tanggalMeninggal = tanggalMeninggal;
       this.tempatMeninggal = tempatMeninggal;
       this.keterangan = keterangan;
       this.nikayah = nikayah;
       this.nikibu = nikibu;
       this.jenisBuat = jenisBuat;
    }
   
    public String getNoAktaKematian() {
        return this.noAktaKematian;
    }
    
    public void setNoAktaKematian(String noAktaKematian) {
        this.noAktaKematian = noAktaKematian;
    }
    public Kartukeluarga getKartukeluarga() {
        return this.kartukeluarga;
    }
    
    public void setKartukeluarga(Kartukeluarga kartukeluarga) {
        this.kartukeluarga = kartukeluarga;
    }
    public Permohonan getPermohonan() {
        return this.permohonan;
    }
    
    public void setPermohonan(Permohonan permohonan) {
        this.permohonan = permohonan;
    }
    public Biodata getBiodata() {
        return this.biodata;
    }
    
    public void setBiodata(Biodata biodata) {
        this.biodata = biodata;
    }
    public Date getTanggalMeninggal() {
        return this.tanggalMeninggal;
    }
    
    public void setTanggalMeninggal(Date tanggalMeninggal) {
        this.tanggalMeninggal = tanggalMeninggal;
    }
    public String getTempatMeninggal() {
        return this.tempatMeninggal;
    }
    
    public void setTempatMeninggal(String tempatMeninggal) {
        this.tempatMeninggal = tempatMeninggal;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }
    public String getNikayah() {
        return this.nikayah;
    }
    
    public void setNikayah(String nikayah) {
        this.nikayah = nikayah;
    }
    public String getNikibu() {
        return this.nikibu;
    }
    
    public void setNikibu(String nikibu) {
        this.nikibu = nikibu;
    }
    public int getJenisBuat() {
        return this.jenisBuat;
    }
    
    public void setJenisBuat(int jenisBuat) {
        this.jenisBuat = jenisBuat;
    }




}


