package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA



/**
 * Biodatacacat generated by hbm2java
 */
public class Biodatacacat  implements java.io.Serializable {


     private Integer biodataCacatId;
     private Cacat cacat;
     private Biodata biodata;
     private int aktif;

    public Biodatacacat() {
    }

    public Biodatacacat(Cacat cacat, Biodata biodata, int aktif) {
       this.cacat = cacat;
       this.biodata = biodata;
       this.aktif = aktif;
    }
   
    public Integer getBiodataCacatId() {
        return this.biodataCacatId;
    }
    
    public void setBiodataCacatId(Integer biodataCacatId) {
        this.biodataCacatId = biodataCacatId;
    }
    public Cacat getCacat() {
        return this.cacat;
    }
    
    public void setCacat(Cacat cacat) {
        this.cacat = cacat;
    }
    public Biodata getBiodata() {
        return this.biodata;
    }
    
    public void setBiodata(Biodata biodata) {
        this.biodata = biodata;
    }
    public int getAktif() {
        return this.aktif;
    }
    
    public void setAktif(int aktif) {
        this.aktif = aktif;
    }




}


