package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA



/**
 * GruppenggunaId generated by hbm2java
 */
public class GruppenggunaId  implements java.io.Serializable {


     private int grupPenggunaId;
     private String username;

    public GruppenggunaId() {
    }

    public GruppenggunaId(int grupPenggunaId, String username) {
       this.grupPenggunaId = grupPenggunaId;
       this.username = username;
    }
   
    public int getGrupPenggunaId() {
        return this.grupPenggunaId;
    }
    
    public void setGrupPenggunaId(int grupPenggunaId) {
        this.grupPenggunaId = grupPenggunaId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GruppenggunaId) ) return false;
		 GruppenggunaId castOther = ( GruppenggunaId ) other; 
         
		 return (this.getGrupPenggunaId()==castOther.getGrupPenggunaId())
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGrupPenggunaId();
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         return result;
   }   


}


