package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hubungandetail generated by hbm2java
 */
public class Hubungandetail  implements java.io.Serializable {


     private Integer hubunganDetailId;
     private Hubungan hubungan;
     private String nama;
     private Set kartukeluargadetailsForStatusHubungan = new HashSet(0);
     private Set kartukeluargadetailsForStatusKawin = new HashSet(0);
     private Set biodatas = new HashSet(0);

    public Hubungandetail() {
    }

	
    public Hubungandetail(Hubungan hubungan, String nama) {
        this.hubungan = hubungan;
        this.nama = nama;
    }
    public Hubungandetail(Hubungan hubungan, String nama, Set kartukeluargadetailsForStatusHubungan, Set kartukeluargadetailsForStatusKawin, Set biodatas) {
       this.hubungan = hubungan;
       this.nama = nama;
       this.kartukeluargadetailsForStatusHubungan = kartukeluargadetailsForStatusHubungan;
       this.kartukeluargadetailsForStatusKawin = kartukeluargadetailsForStatusKawin;
       this.biodatas = biodatas;
    }
   
    public Integer getHubunganDetailId() {
        return this.hubunganDetailId;
    }
    
    public void setHubunganDetailId(Integer hubunganDetailId) {
        this.hubunganDetailId = hubunganDetailId;
    }
    public Hubungan getHubungan() {
        return this.hubungan;
    }
    
    public void setHubungan(Hubungan hubungan) {
        this.hubungan = hubungan;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Set getKartukeluargadetailsForStatusHubungan() {
        return this.kartukeluargadetailsForStatusHubungan;
    }
    
    public void setKartukeluargadetailsForStatusHubungan(Set kartukeluargadetailsForStatusHubungan) {
        this.kartukeluargadetailsForStatusHubungan = kartukeluargadetailsForStatusHubungan;
    }
    public Set getKartukeluargadetailsForStatusKawin() {
        return this.kartukeluargadetailsForStatusKawin;
    }
    
    public void setKartukeluargadetailsForStatusKawin(Set kartukeluargadetailsForStatusKawin) {
        this.kartukeluargadetailsForStatusKawin = kartukeluargadetailsForStatusKawin;
    }
    public Set getBiodatas() {
        return this.biodatas;
    }
    
    public void setBiodatas(Set biodatas) {
        this.biodatas = biodatas;
    }




}


