package org.siak.data;
// Generated Jul 29, 2012 12:49:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kartukeluarga generated by hbm2java
 */
public class Kartukeluarga  implements java.io.Serializable {


     private String noKk;
     private Permohonan permohonan;
     private Biodata biodata;
     private int jenisBuat;
     private Date tanggalBuat;
     private Set kartukeluargadetails = new HashSet(0);
     private Set aktakematians = new HashSet(0);

    public Kartukeluarga() {
    }

	
    public Kartukeluarga(String noKk, Permohonan permohonan, Biodata biodata, int jenisBuat, Date tanggalBuat) {
        this.noKk = noKk;
        this.permohonan = permohonan;
        this.biodata = biodata;
        this.jenisBuat = jenisBuat;
        this.tanggalBuat = tanggalBuat;
    }
    public Kartukeluarga(String noKk, Permohonan permohonan, Biodata biodata, int jenisBuat, Date tanggalBuat, Set kartukeluargadetails, Set aktakematians) {
       this.noKk = noKk;
       this.permohonan = permohonan;
       this.biodata = biodata;
       this.jenisBuat = jenisBuat;
       this.tanggalBuat = tanggalBuat;
       this.kartukeluargadetails = kartukeluargadetails;
       this.aktakematians = aktakematians;
    }
   
    public String getNoKk() {
        return this.noKk;
    }
    
    public void setNoKk(String noKk) {
        this.noKk = noKk;
    }
    public Permohonan getPermohonan() {
        return this.permohonan;
    }
    
    public void setPermohonan(Permohonan permohonan) {
        this.permohonan = permohonan;
    }
    public Biodata getBiodata() {
        return this.biodata;
    }
    
    public void setBiodata(Biodata biodata) {
        this.biodata = biodata;
    }
    public int getJenisBuat() {
        return this.jenisBuat;
    }
    
    public void setJenisBuat(int jenisBuat) {
        this.jenisBuat = jenisBuat;
    }
    public Date getTanggalBuat() {
        return this.tanggalBuat;
    }
    
    public void setTanggalBuat(Date tanggalBuat) {
        this.tanggalBuat = tanggalBuat;
    }
    public Set getKartukeluargadetails() {
        return this.kartukeluargadetails;
    }
    
    public void setKartukeluargadetails(Set kartukeluargadetails) {
        this.kartukeluargadetails = kartukeluargadetails;
    }
    public Set getAktakematians() {
        return this.aktakematians;
    }
    
    public void setAktakematians(Set aktakematians) {
        this.aktakematians = aktakematians;
    }




}


