package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kota generated by hbm2java
 */
public class Kota  implements java.io.Serializable {


     private Integer kotaId;
     private String nama;
     private String username;
     private String sandi;
     private Date waktuLogin;
     private int aktif;
     private Set biodatapindahs = new HashSet(0);

    public Kota() {
    }

	
    public Kota(String nama, String username, String sandi, Date waktuLogin, int aktif) {
        this.nama = nama;
        this.username = username;
        this.sandi = sandi;
        this.waktuLogin = waktuLogin;
        this.aktif = aktif;
    }
    public Kota(String nama, String username, String sandi, Date waktuLogin, int aktif, Set biodatapindahs) {
       this.nama = nama;
       this.username = username;
       this.sandi = sandi;
       this.waktuLogin = waktuLogin;
       this.aktif = aktif;
       this.biodatapindahs = biodatapindahs;
    }
   
    public Integer getKotaId() {
        return this.kotaId;
    }
    
    public void setKotaId(Integer kotaId) {
        this.kotaId = kotaId;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getSandi() {
        return this.sandi;
    }
    
    public void setSandi(String sandi) {
        this.sandi = sandi;
    }
    public Date getWaktuLogin() {
        return this.waktuLogin;
    }
    
    public void setWaktuLogin(Date waktuLogin) {
        this.waktuLogin = waktuLogin;
    }
    public int getAktif() {
        return this.aktif;
    }
    
    public void setAktif(int aktif) {
        this.aktif = aktif;
    }
    public Set getBiodatapindahs() {
        return this.biodatapindahs;
    }
    
    public void setBiodatapindahs(Set biodatapindahs) {
        this.biodatapindahs = biodatapindahs;
    }




}


