package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cacat generated by hbm2java
 */
public class Cacat  implements java.io.Serializable {


     private Integer cacatId;
     private String nama;
     private Set biodatacacats = new HashSet(0);

    public Cacat() {
    }

	
    public Cacat(String nama) {
        this.nama = nama;
    }
    public Cacat(String nama, Set biodatacacats) {
       this.nama = nama;
       this.biodatacacats = biodatacacats;
    }
   
    public Integer getCacatId() {
        return this.cacatId;
    }
    
    public void setCacatId(Integer cacatId) {
        this.cacatId = cacatId;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Set getBiodatacacats() {
        return this.biodatacacats;
    }
    
    public void setBiodatacacats(Set biodatacacats) {
        this.biodatacacats = biodatacacats;
    }




}


