package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Grup generated by hbm2java
 */
public class Grup  implements java.io.Serializable {


     private Integer grupId;
     private String nama;
     private int aktif;
     private Set gruppenggunas = new HashSet(0);

    public Grup() {
    }

	
    public Grup(String nama, int aktif) {
        this.nama = nama;
        this.aktif = aktif;
    }
    public Grup(String nama, int aktif, Set gruppenggunas) {
       this.nama = nama;
       this.aktif = aktif;
       this.gruppenggunas = gruppenggunas;
    }
   
    public Integer getGrupId() {
        return this.grupId;
    }
    
    public void setGrupId(Integer grupId) {
        this.grupId = grupId;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public int getAktif() {
        return this.aktif;
    }
    
    public void setAktif(int aktif) {
        this.aktif = aktif;
    }
    public Set getGruppenggunas() {
        return this.gruppenggunas;
    }
    
    public void setGruppenggunas(Set gruppenggunas) {
        this.gruppenggunas = gruppenggunas;
    }




}


