package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA



/**
 * Gruppengguna generated by hbm2java
 */
public class Gruppengguna  implements java.io.Serializable {


     private GruppenggunaId id;
     private Grup grup;
     private Pengguna pengguna;
     private Integer kecamatanId;
     private Integer kelurahanId;

    public Gruppengguna() {
    }

	
    public Gruppengguna(GruppenggunaId id, Grup grup, Pengguna pengguna) {
        this.id = id;
        this.grup = grup;
        this.pengguna = pengguna;
    }
    public Gruppengguna(GruppenggunaId id, Grup grup, Pengguna pengguna, Integer kecamatanId, Integer kelurahanId) {
       this.id = id;
       this.grup = grup;
       this.pengguna = pengguna;
       this.kecamatanId = kecamatanId;
       this.kelurahanId = kelurahanId;
    }
   
    public GruppenggunaId getId() {
        return this.id;
    }
    
    public void setId(GruppenggunaId id) {
        this.id = id;
    }
    public Grup getGrup() {
        return this.grup;
    }
    
    public void setGrup(Grup grup) {
        this.grup = grup;
    }
    public Pengguna getPengguna() {
        return this.pengguna;
    }
    
    public void setPengguna(Pengguna pengguna) {
        this.pengguna = pengguna;
    }
    public Integer getKecamatanId() {
        return this.kecamatanId;
    }
    
    public void setKecamatanId(Integer kecamatanId) {
        this.kecamatanId = kecamatanId;
    }
    public Integer getKelurahanId() {
        return this.kelurahanId;
    }
    
    public void setKelurahanId(Integer kelurahanId) {
        this.kelurahanId = kelurahanId;
    }




}


