package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pekerjaan generated by hbm2java
 */
public class Pekerjaan  implements java.io.Serializable {


     private Integer pekerjaanId;
     private String nama;
     private Set biodatas = new HashSet(0);
     private Set kartukeluargadetails = new HashSet(0);

    public Pekerjaan() {
    }

	
    public Pekerjaan(String nama) {
        this.nama = nama;
    }
    public Pekerjaan(String nama, Set biodatas, Set kartukeluargadetails) {
       this.nama = nama;
       this.biodatas = biodatas;
       this.kartukeluargadetails = kartukeluargadetails;
    }
   
    public Integer getPekerjaanId() {
        return this.pekerjaanId;
    }
    
    public void setPekerjaanId(Integer pekerjaanId) {
        this.pekerjaanId = pekerjaanId;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Set getBiodatas() {
        return this.biodatas;
    }
    
    public void setBiodatas(Set biodatas) {
        this.biodatas = biodatas;
    }
    public Set getKartukeluargadetails() {
        return this.kartukeluargadetails;
    }
    
    public void setKartukeluargadetails(Set kartukeluargadetails) {
        this.kartukeluargadetails = kartukeluargadetails;
    }




}


