package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pengguna generated by hbm2java
 */
public class Pengguna  implements java.io.Serializable {


     private String username;
     private String sandi;
     private Date waktuLogin;
     private String iplogin;
     private String nama;
     private int aktif;
     private Set gruppenggunas = new HashSet(0);

    public Pengguna() {
    }

	
    public Pengguna(String username, String sandi, Date waktuLogin, String iplogin, String nama, int aktif) {
        this.username = username;
        this.sandi = sandi;
        this.waktuLogin = waktuLogin;
        this.iplogin = iplogin;
        this.nama = nama;
        this.aktif = aktif;
    }
    public Pengguna(String username, String sandi, Date waktuLogin, String iplogin, String nama, int aktif, Set gruppenggunas) {
       this.username = username;
       this.sandi = sandi;
       this.waktuLogin = waktuLogin;
       this.iplogin = iplogin;
       this.nama = nama;
       this.aktif = aktif;
       this.gruppenggunas = gruppenggunas;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getSandi() {
        return this.sandi;
    }
    
    public void setSandi(String sandi) {
        this.sandi = sandi;
    }
    public Date getWaktuLogin() {
        return this.waktuLogin;
    }
    
    public void setWaktuLogin(Date waktuLogin) {
        this.waktuLogin = waktuLogin;
    }
    public String getIplogin() {
        return this.iplogin;
    }
    
    public void setIplogin(String iplogin) {
        this.iplogin = iplogin;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public int getAktif() {
        return this.aktif;
    }
    
    public void setAktif(int aktif) {
        this.aktif = aktif;
    }
    public Set getGruppenggunas() {
        return this.gruppenggunas;
    }
    
    public void setGruppenggunas(Set gruppenggunas) {
        this.gruppenggunas = gruppenggunas;
    }




}


