package org.siak.data;
// Generated Jul 28, 2012 10:43:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Permohonandetail generated by hbm2java
 */
public class Permohonandetail  implements java.io.Serializable {


     private Integer permohonanDetailId;
     private Permohonan permohonan;
     private Biodata biodata;
     private Date tanggalPengajuan;

    public Permohonandetail() {
    }

	
    public Permohonandetail(Permohonan permohonan, Biodata biodata) {
        this.permohonan = permohonan;
        this.biodata = biodata;
    }
    public Permohonandetail(Permohonan permohonan, Biodata biodata, Date tanggalPengajuan) {
       this.permohonan = permohonan;
       this.biodata = biodata;
       this.tanggalPengajuan = tanggalPengajuan;
    }
   
    public Integer getPermohonanDetailId() {
        return this.permohonanDetailId;
    }
    
    public void setPermohonanDetailId(Integer permohonanDetailId) {
        this.permohonanDetailId = permohonanDetailId;
    }
    public Permohonan getPermohonan() {
        return this.permohonan;
    }
    
    public void setPermohonan(Permohonan permohonan) {
        this.permohonan = permohonan;
    }
    public Biodata getBiodata() {
        return this.biodata;
    }
    
    public void setBiodata(Biodata biodata) {
        this.biodata = biodata;
    }
    public Date getTanggalPengajuan() {
        return this.tanggalPengajuan;
    }
    
    public void setTanggalPengajuan(Date tanggalPengajuan) {
        this.tanggalPengajuan = tanggalPengajuan;
    }




}


